FROM node:20-alpine

WORKDIR /app
COPY shared/package.json ./shared/
RUN cd shared && npm install
COPY shared/ ./shared/
COPY server/package.json server/package-lock.json ./server/
RUN cd server && npm ci
COPY server/ ./server/
WORKDIR /app/server
EXPOSE 2567
CMD ["npm", "run", "dev"]
